"""Shared directive data contracts."""

from .artifacts import (
    PUBLISHED_BUNDLE_MAX_BYTES,
    SECTION_CONTENT_MAX_BYTES,
    build_section_content_items,
    calculate_artifact_generation_id,
    canonical_json_bytes,
    canonical_json_hash,
    section_content_item_id,
    serialized_json_size,
)
from ._identity import (
    DIRECTIVE_VERSION_ID_PREFIX,
    MAX_DIRECTIVE_ID_LENGTH,
    MAX_DIRECTIVE_VERSION_ID_LENGTH,
    MAX_DIRECTIVE_VERSION_LENGTH,
    build_directive_version_id,
    directive_storage_key,
    directive_version_storage_key,
    mandate_assignment_item_id,
    normalize_directive_id,
    normalize_directive_version,
    published_directive_version_item_id,
    source_fingerprint,
    validate_directive_version_id,
    validate_published_directive_version_item_id,
)
from .models import (
    DirectiveArtifactLocators,
    DirectiveChunk,
    DirectiveManifest,
    DirectiveMetadata,
    DirectiveRelation,
    DirectiveSection,
    DirectiveSectionContent,
    DirectiveSectionContentDescriptor,
    DirectiveSummary,
    MandateAssignment,
    MandateSnapshot,
    PublishedDirectiveVersion,
    ReviewFinding,
)
from .source_files import (
    normalize_directive_source_prefix,
    validate_directive_source_basename,
)

__all__ = [
    "PUBLISHED_BUNDLE_MAX_BYTES",
    "SECTION_CONTENT_MAX_BYTES",
    "DirectiveArtifactLocators",
    "DirectiveChunk",
    "DirectiveManifest",
    "DirectiveMetadata",
    "DirectiveRelation",
    "DirectiveSection",
    "DirectiveSectionContent",
    "DirectiveSectionContentDescriptor",
    "DirectiveSummary",
    "DIRECTIVE_VERSION_ID_PREFIX",
    "MAX_DIRECTIVE_ID_LENGTH",
    "MAX_DIRECTIVE_VERSION_ID_LENGTH",
    "MAX_DIRECTIVE_VERSION_LENGTH",
    "MandateAssignment",
    "MandateSnapshot",
    "PublishedDirectiveVersion",
    "ReviewFinding",
    "build_section_content_items",
    "calculate_artifact_generation_id",
    "canonical_json_bytes",
    "canonical_json_hash",
    "build_directive_version_id",
    "directive_storage_key",
    "directive_version_storage_key",
    "mandate_assignment_item_id",
    "normalize_directive_id",
    "normalize_directive_version",
    "normalize_directive_source_prefix",
    "published_directive_version_item_id",
    "section_content_item_id",
    "serialized_json_size",
    "source_fingerprint",
    "validate_directive_source_basename",
    "validate_directive_version_id",
    "validate_published_directive_version_item_id",
]
